apiVersion: v1
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels.selector" . | indent 4 }}
kind: ConfigMap
data:
  cron-schedule: '{{ .Values.esCurator.config.cronSchedule }}'
  es-host: {{ .Values.esCurator.config.esHost }}
  es-port: '{{ .Values.esCurator.config.esPort }}'
  snapshot-name: {{ .Values.esCurator.config.snapshotName }}
  bucket-name: {{ .Values.esCurator.config.bucketName }}
  bucket-base-path: {{ .Values.esCurator.config.bucketBasePath }}
  aws-region: {{ .Values.esCurator.config.awsRegion }}
  time-unit: {{ .Values.esCurator.config.timeUnit }}
  older-than: '{{ .Values.esCurator.config.olderThan }}'
  loglevel: '{{ .Values.esCurator.config.loglevel }}'
